import { ProcessedDocument, StudentRecord } from '../types/student';

export const SAMPLE_STUDENTS: StudentRecord[] = [
  {
    stt_trong_file_tong: 1,
    stt: 1,
    ho: 'Nguyễn Văn',
    ten: 'An',
    ngay_sinh: '15/08/2001',
    noi_sinh: 'Hà Nội',
    xep_loai: 'Xuất sắc',
    so_vao_so: 'CN-2025/001',
    so_hieu_bang: 'B1234567',
    quyet_dinh_tot_nghiep_so: '3999',
    quyet_dinh_tot_nghiep_ngay: '20/06/2025',
    gioi_tinh: 'Nam',
    quoc_tich: 'Việt Nam',
    lop: 'K65-CNTT',
    dao_tao_tu_nam: '2020',
    dao_tao_den_nam: '2025',
    nganh_dao_tao: 'Công nghệ thông tin',
    ma_chuong_trinh_dao_tao: '7480201',
    don_vi_cap_bang: 'Trường Đại học Bách Khoa',
    ghi_chu: '',
    cccd: '001201008899',
    ngay_cap: '10/05/2021',
    noi_cap: 'Cục Cảnh sát QLHC về trật tự xã hội',
  },
  {
    stt_trong_file_tong: 2,
    stt: 2,
    ho: 'Trần Thị',
    ten: 'Bích',
    ngay_sinh: '02/11/2001',
    noi_sinh: 'Đà Nẵng',
    xep_loai: 'Giỏi',
    so_vao_so: 'CN-2025/002',
    so_hieu_bang: 'B1234568',
    quyet_dinh_tot_nghiep_so: '3999',
    quyet_dinh_tot_nghiep_ngay: '20/06/2025',
    gioi_tinh: 'Nữ',
    quoc_tich: 'Việt Nam',
    lop: 'K65-KT',
    dao_tao_tu_nam: '2020',
    dao_tao_den_nam: '2025',
    nganh_dao_tao: 'Kế toán',
    ma_chuong_trinh_dao_tao: '7340301',
    don_vi_cap_bang: 'Trường Đại học Bách Khoa',
    ghi_chu: '',
    cccd: '048201004567',
    ngay_cap: '14/02/2022',
    noi_cap: 'Cục Cảnh sát QLHC về trật tự xã hội',
  },
];

export function createSampleDocument(): ProcessedDocument {
  return {
    id: 'sample_doc_demo',
    fileHash: 'sample_hash_12345',
    fileName: 'Mau_Danh_Sach_Bang_Tot_Nghiep_Dai_Hoc_2025.pdf',
    fileSize: 2450000,
    totalPages: 12,
    estimatedTokens: 26400,
    isDigital: true,
    averageComplexity: 1.5,
    batches: [
      {
        batchIndex: 0,
        startPage: 1,
        endPage: 12,
        status: 'completed',
        retryCount: 0,
        tokensUsed: 26400,
        durationMs: 3400,
        verifiedByAI: true,
        result: {
          decision_number: '3999',
          decision_date: '20/06/2025',
          students: SAMPLE_STUDENTS,
        },
      },
    ],
    mergedStudents: SAMPLE_STUDENTS,
    decisionNumber: '3999',
    decisionDate: '20/06/2025',
    stage: 'completed',
    cached: false,
    totalTokens: 26400,
    totalCostUsd: 0.0028,
    totalDurationMs: 3400,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  };
}
